# Pandas - Data analysis and Manipulation tool
## built on top of numpy

In [2]:
import pandas as pd

In [5]:
info = {
    "Name" : ["Ajay", "Shreyas", "Saraswath"],
    "CGPA" : [7.7, 7.9, 8.5]
}

df = pd.DataFrame(info)

print(df)

        Name  CGPA
0       Ajay   7.7
1    Shreyas   7.9
2  Saraswath   8.5

In [6]:
df

        Name  CGPA
0       Ajay   7.7
1    Shreyas   7.9
2  Saraswath   8.5

## Series in pandas
### 1D labelled arrays

In [ ]:
s = pd.Series([1,2,3,4,5])

print(s)
print(type(s))

# index - positions
print(s[2])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3
4

In [13]:
# labels = named index

s = pd.Series([22, 23, 24, 25], index = ["ajay", "shreyas", "saraswath", "nick"])

print(s)
print(s["ajay"])
print(s["nick"])
print(s.index)

ajay         22
shreyas      23
saraswath    24
nick         25
dtype: int64
22
25
Index(['ajay', 'shreyas', 'saraswath', 'nick'], dtype='object')

## functions associated with series
- Homogeneous - holds same values like numpy
- vectorized operations
- Handles missing values with NaN
- Mutable values, Immutable size

In [18]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100

changed_s1 = s1.drop(0) # original s1 is still intact - immutable size
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

## Different ways of creating a dataframe
- from dictionaries

In [7]:
info = {
    "Name" : ["Khaja", "Fairoza", "Roshan"],
    "Age" : [22, 21, 18]
}
df = pd.DataFrame(info)

print(df)
print(type(df))
print(df.index) # returns labels in the form of a range
print(df.columns)

      Name  Age
0    Khaja   22
1  Fairoza   21
2   Roshan   18
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age'], dtype='object')

- from list of lists

In [8]:
df = pd.DataFrame([["Shaik", 23], ["Abhi", 36]], columns = ["Name", "age"])
print(df)

    Name  age
0  Shaik   23
1   Abhi   36

- from numpy arrays

In [9]:
import numpy as np
np_arr = np.array([[1,2,3,4], [5,6,7,8]])
df = pd.DataFrame(np_arr, columns=["A", "B", "C", "D"])

df

   A  B  C  D
0  1  2  3  4
1  5  6  7  8

### loading data from different sources
- json

In [17]:
data = pd.read_json("data files/employee_data.json")
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

- csv

In [16]:
data = pd.read_csv("data files/employee_data.csv")
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000