# Data Transformation - Feature engineering

### it is the process of adding a new feature/column so that the accuracy of the model increases

In [39]:
import pandas as pd 
df = pd.read_csv("data files/raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [40]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

### apply() - it is a higher order function which takes another function as parameter to perform functions like adding a new column

In [41]:
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

### map() - changing the existing values and mapping it with the new ones

In [42]:
# change the values of: Male -> M, Female -> F, Unknown -> U

gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}

df2["gender"] = df2["gender"].map(gender_map)

df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [43]:
# assign() - creating new columns by assigning them some values
# example: increase the salary by 10%

df2.assign(new_income = df["income"] * 1.1)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [44]:
# replace(old, new) - used to replace the old value from the new

df2["country"] = df2["country"].replace("USA", "United States") 
df2

    id          name   age        country gender   income  tax
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
2    2    Jane Smith   NaN         Canada      F  62000.0  20%
3    3          Alex   NaN  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F      NaN  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
6    6           NaN  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%

In [45]:
# rename(columns = {old : new}) - rename rows and columns
# if you want to rename all the colums:

df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax"]
df2

    Id          Name   Age        Country Gender   Income  Tax
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
2    2    Jane Smith   NaN         Canada      F  62000.0  20%
3    3          Alex   NaN  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F      NaN  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
6    6           NaN  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%

In [46]:
# but if you want to rename a single column?

df2.rename(columns= {"Income" : "Salary"}) # renaming columns

    Id          Name   Age        Country Gender   Salary  Tax
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
2    2    Jane Smith   NaN         Canada      F  62000.0  20%
3    3          Alex   NaN  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F      NaN  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
6    6           NaN  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%

In [47]:
df2.rename(index= {1 : "First"}) # renaming row

       Id          Name   Age        Country Gender   Income  Tax
0       1      John Doe  29.0  United States      M  55000.0  10%
First   1      John Doe  29.0  United States      M  55000.0  10%
2       2    Jane Smith   NaN         Canada      F  62000.0  20%
3       3          Alex   NaN  United States      U  47000.0  10%
4       4  Maria Garcia  34.0          Spain      F      NaN  10%
5       5        Li Wei  27.0          China      M  51000.0  10%
6       6           NaN  45.0          India      F  73000.0  20%
7       7    Ahmed Khan  38.0            NaN      M  68000.0  20%
8       8    Rachel Lee  29.0  United States      F  62000.0  20%
9       9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%
10     10   Emily Davis  31.0  United States    NaN  58000.0  10%

In [48]:
# sorted_values() - sorts a column or a set of columns

df2 = df2.fillna(50)
df2

    Id          Name   Age        Country Gender   Income  Tax
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
2    2    Jane Smith  50.0         Canada      F  62000.0  20%
3    3          Alex  50.0  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F     50.0  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
6    6            50  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0  10%

In [49]:
df2.sort_values("Income") # sort based on income

    Id          Name   Age        Country Gender   Income  Tax
4    4  Maria Garcia  34.0          Spain      F     50.0  10%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
3    3          Alex  50.0  United States      U  47000.0  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
0    1      John Doe  29.0  United States      M  55000.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0  10%
2    2    Jane Smith  50.0         Canada      F  62000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0  20%
6    6            50  45.0          India      F  73000.0  20%

In [50]:
sorted_df = df2.sort_values(["Income", "Age"]) # sort based on income and age
sorted_df

    Id          Name   Age        Country Gender   Income  Tax
4    4  Maria Garcia  34.0          Spain      F     50.0  10%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
3    3          Alex  50.0  United States      U  47000.0  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0  10%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
2    2    Jane Smith  50.0         Canada      F  62000.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0  20%
6    6            50  45.0          India      F  73000.0  20%

In [51]:
df2.sort_values("Income", ascending=False) # sort in descending order

    Id          Name   Age        Country Gender   Income  Tax
6    6            50  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0  20%
2    2    Jane Smith  50.0         Canada      F  62000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
10  10   Emily Davis  31.0  United States     50  58000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
0    1      John Doe  29.0  United States      M  55000.0  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
3    3          Alex  50.0  United States      U  47000.0  10%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
4    4  Maria Garcia  34.0          Spain      F     50.0  10%

In [52]:
sorted_df.sort_index() # sort based on index values

    Id          Name   Age        Country Gender   Income  Tax
0    1      John Doe  29.0  United States      M  55000.0  10%
1    1      John Doe  29.0  United States      M  55000.0  10%
2    2    Jane Smith  50.0         Canada      F  62000.0  20%
3    3          Alex  50.0  United States      U  47000.0  10%
4    4  Maria Garcia  34.0          Spain      F     50.0  10%
5    5        Li Wei  27.0          China      M  51000.0  10%
6    6            50  45.0          India      F  73000.0  20%
7    7    Ahmed Khan  38.0             50      M  68000.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0  20%
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
10  10   Emily Davis  31.0  United States     50  58000.0  10%

In [53]:
sorted_df.reset_index() # the data is sorted, index is preserved and it has added new labels

    index  Id          Name   Age        Country Gender   Income  Tax
0       4   4  Maria Garcia  34.0          Spain      F     50.0  10%
1       9   9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
2       3   3          Alex  50.0  United States      U  47000.0  10%
3       5   5        Li Wei  27.0          China      M  51000.0  10%
4       0   1      John Doe  29.0  United States      M  55000.0  10%
5       1   1      John Doe  29.0  United States      M  55000.0  10%
6      10  10   Emily Davis  31.0  United States     50  58000.0  10%
7       8   8    Rachel Lee  29.0  United States      F  62000.0  20%
8       2   2    Jane Smith  50.0         Canada      F  62000.0  20%
9       7   7    Ahmed Khan  38.0             50      M  68000.0  20%
10      6   6            50  45.0          India      F  73000.0  20%

In [54]:
sorted_df.reset_index(drop= True) # removes preserved indexes

    Id          Name   Age        Country Gender   Income  Tax
0    4  Maria Garcia  34.0          Spain      F     50.0  10%
1    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%
2    3          Alex  50.0  United States      U  47000.0  10%
3    5        Li Wei  27.0          China      M  51000.0  10%
4    1      John Doe  29.0  United States      M  55000.0  10%
5    1      John Doe  29.0  United States      M  55000.0  10%
6   10   Emily Davis  31.0  United States     50  58000.0  10%
7    8    Rachel Lee  29.0  United States      F  62000.0  20%
8    2    Jane Smith  50.0         Canada      F  62000.0  20%
9    7    Ahmed Khan  38.0             50      M  68000.0  20%
10   6            50  45.0          India      F  73000.0  20%

In [ ]:
sorted_df["Ranking"] = sorted_df["Income"].rank()
sorted_df
# you can observe, the 5.5 which is a bit sus, but thats the average b/w 5 and 6 
# and for the tie rows, it will be the same i.e., 5.5

    Id          Name   Age        Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0          Spain      F     50.0  10%      1.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%      2.0
3    3          Alex  50.0  United States      U  47000.0  10%      3.0
5    5        Li Wei  27.0          China      M  51000.0  10%      4.0
0    1      John Doe  29.0  United States      M  55000.0  10%      5.5
1    1      John Doe  29.0  United States      M  55000.0  10%      5.5
10  10   Emily Davis  31.0  United States     50  58000.0  10%      7.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%      8.5
2    2    Jane Smith  50.0         Canada      F  62000.0  20%      8.5
7    7    Ahmed Khan  38.0             50      M  68000.0  20%     10.0
6    6            50  45.0          India      F  73000.0  20%     11.0

In [56]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending= False)
sorted_df

    Id          Name   Age        Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0          Spain      F     50.0  10%     11.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%     10.0
3    3          Alex  50.0  United States      U  47000.0  10%      9.0
5    5        Li Wei  27.0          China      M  51000.0  10%      8.0
0    1      John Doe  29.0  United States      M  55000.0  10%      6.5
1    1      John Doe  29.0  United States      M  55000.0  10%      6.5
10  10   Emily Davis  31.0  United States     50  58000.0  10%      5.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%      3.5
2    2    Jane Smith  50.0         Canada      F  62000.0  20%      3.5
7    7    Ahmed Khan  38.0             50      M  68000.0  20%      2.0
6    6            50  45.0          India      F  73000.0  20%      1.0

### there are several options on how you want to resove tie of the ranks, you can specify a param in the rank function i.e., rank(method= dense, min, max)

In [62]:
sorted_df["Ranking"] = sorted_df["Income"].rank(method= "dense") # tie -> same number
sorted_df

    Id          Name   Age        Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0          Spain      F     50.0  10%      1.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%      2.0
3    3          Alex  50.0  United States      U  47000.0  10%      3.0
5    5        Li Wei  27.0          China      M  51000.0  10%      4.0
0    1      John Doe  29.0  United States      M  55000.0  10%      5.0
1    1      John Doe  29.0  United States      M  55000.0  10%      5.0
10  10   Emily Davis  31.0  United States     50  58000.0  10%      6.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%      7.0
2    2    Jane Smith  50.0         Canada      F  62000.0  20%      7.0
7    7    Ahmed Khan  38.0             50      M  68000.0  20%      8.0
6    6            50  45.0          India      F  73000.0  20%      9.0

In [ ]:
sorted_df["Ranking"] = sorted_df["Income"].rank(method= "min") # tie -> min will be repaeted
sorted_df

    Id          Name   Age        Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0          Spain      F     50.0  10%      1.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%      2.0
3    3          Alex  50.0  United States      U  47000.0  10%      3.0
5    5        Li Wei  27.0          China      M  51000.0  10%      4.0
0    1      John Doe  29.0  United States      M  55000.0  10%      5.0
1    1      John Doe  29.0  United States      M  55000.0  10%      5.0
10  10   Emily Davis  31.0  United States     50  58000.0  10%      7.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%      8.0
2    2    Jane Smith  50.0         Canada      F  62000.0  20%      8.0
7    7    Ahmed Khan  38.0             50      M  68000.0  20%     10.0
6    6            50  45.0          India      F  73000.0  20%     11.0

In [ ]:
sorted_df["Ranking"] = sorted_df["Income"].rank(method= "max") # tie -> max will be repeated
sorted_df

    Id          Name   Age        Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0          Spain      F     50.0  10%      1.0
9    9   Carlos Ruiz  50.0         Mexico      M  45000.0  10%      2.0
3    3          Alex  50.0  United States      U  47000.0  10%      3.0
5    5        Li Wei  27.0          China      M  51000.0  10%      4.0
0    1      John Doe  29.0  United States      M  55000.0  10%      6.0
1    1      John Doe  29.0  United States      M  55000.0  10%      6.0
10  10   Emily Davis  31.0  United States     50  58000.0  10%      7.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%      9.0
2    2    Jane Smith  50.0         Canada      F  62000.0  20%      9.0
7    7    Ahmed Khan  38.0             50      M  68000.0  20%     10.0
6    6            50  45.0          India      F  73000.0  20%     11.0

### Reordering columns

In [65]:
sorted_df[["Name", "Age", "Country", "Gender", "Income", "Tax", "Id"]]

            Name   Age        Country Gender   Income  Tax  Id
4   Maria Garcia  34.0          Spain      F     50.0  10%   4
9    Carlos Ruiz  50.0         Mexico      M  45000.0  10%   9
3           Alex  50.0  United States      U  47000.0  10%   3
5         Li Wei  27.0          China      M  51000.0  10%   5
0       John Doe  29.0  United States      M  55000.0  10%   1
1       John Doe  29.0  United States      M  55000.0  10%   1
10   Emily Davis  31.0  United States     50  58000.0  10%  10
8     Rachel Lee  29.0  United States      F  62000.0  20%   8
2     Jane Smith  50.0         Canada      F  62000.0  20%   2
7     Ahmed Khan  38.0             50      M  68000.0  20%   7
6             50  45.0          India      F  73000.0  20%   6