# Pandas - Data analysis and Manipulation tool
## built on top of numpy

In [ ]:
import pandas as pd

In [5]:
info = {
    "Name" : ["Ajay", "Shreyas", "Saraswath"],
    "CGPA" : [7.7, 7.9, 8.5]
}

df = pd.DataFrame(info)

print(df)

        Name  CGPA
0       Ajay   7.7
1    Shreyas   7.9
2  Saraswath   8.5

In [6]:
df

        Name  CGPA
0       Ajay   7.7
1    Shreyas   7.9
2  Saraswath   8.5

## Series in pandas
### 1D labelled arrays

In [ ]:
s = pd.Series([1,2,3,4,5])

print(s)
print(type(s))

# index - positions
print(s[2])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3
4

In [13]:
# labels = named index

s = pd.Series([22, 23, 24, 25], index = ["ajay", "shreyas", "saraswath", "nick"])

print(s)
print(s["ajay"])
print(s["nick"])
print(s.index)

ajay         22
shreyas      23
saraswath    24
nick         25
dtype: int64
22
25
Index(['ajay', 'shreyas', 'saraswath', 'nick'], dtype='object')

## functions associated with series
- Homogeneous - holds same values like numpy
- vectorized operations
- Handles missing values with NaN
- Mutable values, Immutable size

In [18]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10, 20, 30, 40, 50])

print(s1 + s2)

s1[0] = 100

changed_s1 = s1.drop(0) # original s1 is still intact - immutable size
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

## Different ways of creating a dataframe
- from dictionaries

In [7]:
info = {
    "Name" : ["Khaja", "Fairoza", "Roshan"],
    "Age" : [22, 21, 18]
}
df = pd.DataFrame(info)

print(df)
print(type(df))
print(df.index) # returns labels in the form of a range
print(df.columns)

      Name  Age
0    Khaja   22
1  Fairoza   21
2   Roshan   18
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age'], dtype='object')

- from list of lists

In [8]:
df = pd.DataFrame([["Shaik", 23], ["Abhi", 36]], columns = ["Name", "age"])
print(df)

    Name  age
0  Shaik   23
1   Abhi   36

- from numpy arrays

In [9]:
import numpy as np
np_arr = np.array([[1,2,3,4], [5,6,7,8]])
df = pd.DataFrame(np_arr, columns=["A", "B", "C", "D"])

df

   A  B  C  D
0  1  2  3  4
1  5  6  7  8

### loading data from different sources
- json

In [17]:
data = pd.read_json("data files/employee_data.json")
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

- csv

In [5]:
data = pd.read_csv("data files/employee_data.csv")
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

### methods used with dataframe

In [ ]:
df.head() # returns the first 5 rows of the dataset

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [7]:
df.tail() # last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [ ]:
df.sample() # returns random sample row, you can specify number of rows

   ID   Name  Age Department  Salary
9  10  Julia   30    Finance   60000

In [ ]:
df.info() # summary of the entire dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [ ]:
df.shape # return dimensions of the dataset

(10, 5)

In [ ]:
df.describe() # performs some calculations on numerical columns

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [ ]:
df.columns # returns the columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [ ]:
df.nunique() # gives a count of unique values in each column

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [2]:
import pandas as pd
df = pd.read_csv("data files/globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

### acessing the columns

In [ ]:
df["country"]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [18]:
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

### accessing the rows
- by label - loc
- by index - iloc

In [ ]:
df.loc[3]
df.loc[0:2] # start ind : end ind (inclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [ ]:
df.iloc[2]
df.iloc[0:2] # start ind : end ind (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

### individual cells
#### basically we use loc and iloc itself

In [ ]:
df.loc[0, "city"] # basically we don't use loc and iloc to print scalar values

'New York'

In [5]:
df.loc[0:2, ["city", "country", "aqi"]]

       city country  aqi
0  New York      US  108
1  New York      US   90
2  New York      US   84

In [ ]:
df.iloc[0:2, 1:5] # iloc doesn't accept string values as it deals only with indexes

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

### for accessing single (scalar) values, we can use at, iat

In [3]:
df.at[0, "city"]

'New York'

In [4]:
df.iat[0, 2]

'New York'

### another thing to remember, just like numpy pandas also returns views not copies. you cannot always remember which will rerurn copy or view so better to use .copy method whenever you want to make changes to the dataset values